---
version: "3"
services:
  issue:
    image: neilpang/acme.sh
    command: |
      --issue --dns -d *.shubhamtatvamasi.com
      --yes-I-know-dns-manual-mode-enough-go-ahead-please
  renew:
    image: neilpang/acme.sh
    command: |
      --renew -d *.shubhamtatvamasi.com
      --yes-I-know-dns-manual-mode-enough-go-ahead-please
...
