---
version: "3"
services:
  issue:
    container_name: letsencrypt
    image: neilpang/acme.sh
    volumes:
      - ./acme.sh/:/acme.sh/
    command: |
      --issue --dns -d *.shubhamtatvamasi.com -d shubhamtatvamasi.com
      --yes-I-know-dns-manual-mode-enough-go-ahead-please
      --keylength ec-384
  renew:
    container_name: letsencrypt
    image: neilpang/acme.sh
    volumes:
      - ./acme.sh/:/acme.sh/
    command: |
      --renew -d *.shubhamtatvamasi.com -d shubhamtatvamasi.com
      --yes-I-know-dns-manual-mode-enough-go-ahead-please --force
      --ecc
  help:
    container_name: letsencrypt
    image: neilpang/acme.sh
    command: --help   
...
