---
version: "3"
services:
  issue:
    container_name: letsencrypt
    image: neilpang/acme.sh
    env_file:
      - godaddy.keys
    volumes:
      - ./acme.sh/:/acme.sh/
    command: |
      --issue
      -d shubhamtatvamasi.com
      -d *.shubhamtatvamasi.com
      --always-force-new-domain-key
      --keylength ec-256
      --dns dns_gd
      --force
  help:
    container_name: letsencrypt
    image: neilpang/acme.sh
    command: --help
...
